version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_blog
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
